[build]
# The index HTML file to drive the bundling process
target = "index.html"
# Build in release mode (CI can also pass --release)
release = false
# The output dir for all final assets
dist = "dist"
# The public URL from which assets are to be served
public_url = "/"
# Whether to include hash values in the output file names
filehash = true
# Whether to inject scripts (and module preloads) into the finalized output
inject_scripts = true
# Control minification
minify = "on_release" # can be one of: never, on_release, always

[tools.wasm-opt]
# Disable wasm-opt to avoid bulk memory errors
skip = true

[watch]
# Paths to watch. The build.target's parent folder is watched by default
watch = ["src", "index.html"]
# Paths to ignore
ignore = []

[serve]
# The address to serve on
addresses = ["127.0.0.1"]
# The port to serve on
port = 8080
# Open a browser tab once the initial build is complete
open = false
# Whether to disable fallback to index.html for missing files
# no_spa = false
# Disable auto-reload of the web app
# no_autoreload = false
# Disable error reporting
# no_error_reporting = false
