# =============================================================================
# GraphRAG Configuration Template - ACADEMIC RESEARCH & SCIENTIFIC PAPERS
# =============================================================================
# Optimized for: Research papers, academic articles, scientific studies, theses
# Based on 2024 research: balanced parameters for academic precision and concept discovery
# Use cases: Scientific papers, research articles, academic literature reviews, theses
# 🎯 FULLY DYNAMIC: Works with any academic domain without hardcoded assumptions
# =============================================================================

[general]
# General configuration
input_document_path = "path/to/your/research_paper.pdf"
output_dir = "./output/academic_analysis"
log_level = "info"
max_threads = 4
enable_profiling = true

[pipeline]
# Processing pipeline optimized for academic content
workflows = ["extract_text", "extract_entities", "build_graph", "detect_communities"]
parallel_execution = true

[pipeline.text_extraction]
# ACADEMIC CHUNKING: Research shows 512-1024 tokens optimal for academic concepts
# Reference: Multi-Dataset Analysis (2024) "Optimal Chunking for Academic Content"
chunk_size = 1024             # Larger chunks for complete academic concepts (Multi-Dataset 2024)
chunk_overlap = 200           # 20% overlap for concept continuity (Pinecone 2024)
min_chunk_size = 256          # Ensures complete academic statements
clean_control_chars = true
normalize_whitespace = true

[pipeline.entity_extraction]
# ACADEMIC ENTITY TYPES: Specialized for research and scientific content
model_name = "llama3.1:8b"
temperature = 0.15            # Low-moderate for academic precision with some flexibility (IBM 2024)
max_tokens = 1200             # Higher for detailed academic descriptions
entity_types = [
    "RESEARCHER",             # Authors, scientists, researchers
    "INSTITUTION",            # Universities, research institutes
    "THEORY",                 # Scientific theories, frameworks
    "METHODOLOGY",            # Research methods, approaches
    "DATASET",                # Data sources, datasets, corpora
    "EXPERIMENT",             # Experimental procedures, studies
    "FINDING",                # Research findings, results
    "HYPOTHESIS",             # Research hypotheses, predictions
    "VARIABLE",               # Independent/dependent variables
    "METRIC",                 # Performance metrics, measurements
    "CITATION",               # References, citations
    "PUBLICATION",            # Journals, conferences, books
    "CONCEPT",                # Abstract concepts, definitions
    "FIELD",                  # Academic fields, disciplines
    "TOOL",                   # Research tools, software, equipment
    "STATISTIC",              # Statistical measures, p-values
    "MODEL",                  # Mathematical/computational models
    "ALGORITHM"               # Algorithms, computational methods
]
confidence_threshold = 0.7    # Moderate-high for academic accuracy (Azure AI 2024)

[pipeline.entity_extraction.filters]
# ACADEMIC FILTERING: Pattern matching for academic terminology
min_entity_length = 2
max_entity_length = 200       # Longer for complex academic terms
allowed_patterns = [
    "^[A-Z][a-zA-Z\\s\\-\\.]+$",                    # Academic proper nouns
    "^[A-Z][a-z]+\\s+(et\\s+al\\.?|and\\s+[A-Z][a-z]+)$", # Author citations
    "^[A-Z][A-Z0-9\\-]+$",                           # Acronyms
    "^p\\s*[<>=]\\s*0\\.\\d+$",                     # P-values
    "^\\d+(\\.\\d+)?%$",                             # Percentages
    "^[A-Za-z]+\\s*\\(\\d{4}\\)$"                   # Author (year) citations
]
excluded_patterns = [
    "^(the|and|but|for|with|from|that|this|however|therefore)$",
    "^(figure|table|section|chapter)$"
]

[pipeline.graph_building]
# ACADEMIC GRAPH: Focus on research relationships and concept connections
relation_scorer = "cosine_similarity"
min_relation_score = 0.5      # Moderate threshold for academic concept relationships (ArXiv 2024)
max_connections_per_node = 30 # Allow complex academic concept networks
bidirectional_relations = true
concept_centrality_boost = 1.4   # Emphasize key academic concepts

[pipeline.community_detection]
# ACADEMIC COMMUNITIES: Research themes, methodological groups
algorithm = "leiden"          # Reference: SpringerLink (2024) "Community Detection Algorithms"
resolution = 0.7              # Balanced academic concept groupings (SpringerLink 2024)
min_community_size = 3
max_community_size = 25       # Larger groups for academic concepts

[text_processing]
# ACADEMIC TEXT PROCESSING
enabled = true
chunk_size = 1024             # Consistent with pipeline
chunk_overlap = 200           # 20% overlap for concept continuity
min_chunk_size = 256
max_chunk_size = 2048         # Allow longer chunks for complex academic discussions
normalize_whitespace = true
remove_artifacts = true
extract_keywords = true
keyword_min_score = 0.2       # Moderate threshold for academic keywords

[entity_extraction]
# ACADEMIC ENTITY OPTIMIZATION
enabled = true
min_confidence = 0.7          # High confidence for academic precision
use_gleaning = true
max_gleaning_rounds = 3       # Standard rounds for academic clarity
gleaning_improvement_threshold = 0.1
semantic_merging = true
merge_similarity_threshold = 0.8      # High precision for academic concept merging
automatic_linking = true
linking_confidence_threshold = 0.75

[entity_extraction.gleaning]
# ACADEMIC GLEANING: Focus on research concepts and methodologies
focus_areas = ["THEORY", "METHODOLOGY", "FINDING", "HYPOTHESIS", "CONCEPT"]
context_window = 300          # Larger context for academic concept understanding
llm_temperature = 0.1         # Low for academic consistency
academic_context = true
citation_aware = true

[graph_construction]
# ACADEMIC GRAPH PARAMETERS
enabled = true
incremental_updates = true
use_pagerank = true
pagerank_damping = 0.85       # Standard damping for academic importance (Neo4j 2024)
pagerank_iterations = 60     # Moderate iterations for academic concept networks
pagerank_convergence = 0.0001
extract_relationships = true
relationship_confidence_threshold = 0.6  # Moderate for academic concept relationships
research_relationship_boost = 1.3        # Boost research-related connections

[vector_processing]
# ACADEMIC SEARCH: Balanced precision and discovery
enabled = true
embedding_model = "nomic-embed-text"
embedding_dimensions = 768
use_hnsw_index = true
hnsw_ef_construction = 250    # Higher for academic concept search
hnsw_m = 20                   # Balanced connections for academic content
similarity_threshold = 0.7    # Moderate-high for academic precision

[query_processing]
# ACADEMIC QUERY PROCESSING
enabled = true
use_advanced_pipeline = true
use_intent_classification = true
use_concept_extraction = true
use_temporal_parsing = true    # Important for research timelines
confidence_threshold = 0.5     # Moderate for academic exploration

[query_processing.intent_classification]
# ACADEMIC INTENT PATTERNS
research_patterns = ["research", "study", "investigation", "analysis", "examination"]
method_patterns = ["method", "methodology", "approach", "technique", "procedure"]
result_patterns = ["result", "finding", "outcome", "conclusion", "evidence"]
theory_patterns = ["theory", "framework", "model", "hypothesis", "concept"]
comparison_patterns = ["compare", "versus", "difference", "similarity", "contrast"]

[query_processing.prompt_templates]
# ACADEMIC PROMPTS: Specialized for research analysis
research = """Based on the following academic context, provide a detailed research analysis for: {query}

Context:
{context}

Research Analysis:"""

methodology = """Analyze the research methodologies and approaches described in the context for: {query}

Context:
{context}

Methodology Analysis:"""

findings = """Summarize the research findings and their implications described in the context for: {query}

Context:
{context}

Findings Summary:"""

[ollama]
# ACADEMIC LLM: Balanced for research analysis
enabled = true
host = "http://localhost"
port = 11434
chat_model = "llama3.1:8b"
embedding_model = "nomic-embed-text"
timeout_seconds = 120         # Higher timeout for complex academic analysis
max_retries = 3
fallback_to_hash = false
max_tokens = 1500             # Higher for detailed academic responses
temperature = 0.2             # Research: 0.1-0.3 optimal for academic analysis (IBM 2024)

[ollama.generation]
# ACADEMIC GENERATION: Balanced precision and comprehensiveness
temperature = 0.25            # Low-moderate for academic accuracy with flexibility (phData 2024)
top_p = 0.9                   # Broader consideration for academic nuance (AnalyticsVidhya 2024)
max_tokens = 2000             # Longer for comprehensive academic analysis
stream = false

[performance]
# ACADEMIC PERFORMANCE: Quality focus
batch_processing = true
batch_size = 40               # Moderate batches for academic content
worker_threads = 4
memory_limit_mb = 8192        # Higher memory for complex academic graphs
cache_embeddings = true

[monitoring]
# ACADEMIC MONITORING
enabled = true
track_concept_accuracy = true
track_citation_coverage = true
track_research_coherence = true

# =============================================================================
# RESEARCH REFERENCES:
# - Multi-Dataset Analysis (2024): "Optimal Chunking for Academic Content"
# - Pinecone (2024): "Chunking Strategies for LLM Applications"
# - Azure AI (2024): "Custom NER evaluation metrics"
# - IBM (2024): "Understanding LLM Temperature"
# - phData (2024): "How to Tune LLM Parameters for Top Performance"
# - AnalyticsVidhya (2024): "Understanding OpenAI's Temperature and Top_p Parameters"
# - Neo4j (2024): "PageRank Algorithm Implementation and Optimization"
# - ArXiv (2024): "Similarity Thresholds in Knowledge Graph Construction"
# - SpringerLink (2024): "Community Detection Algorithms for Large Networks"
#
# USAGE INSTRUCTIONS:
# 1. Set input_document_path to your research paper/academic document
# 2. Adjust output_dir for your project
# 3. Run: cargo run --example tom_sawyer_toml_config
# 4. Query: cargo run --example query_graphrag -- "What methodology was used?"
#
# OPTIMIZED FOR:
# - Research methodology analysis
# - Concept and theory mapping
# - Academic literature synthesis
# - Citation and reference tracking
# - Scientific finding extraction
# =============================================================================